name: Code quality

on:
  pull_request:
  push:
    branches:
      - master
    tags-ignore:
      - '**'

jobs:
  codequality:
    name: Code quality
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Format
        run: make fmt_check