name: Code quality

on:
  pull_request:
  push:
    branches:
      - master
    tags-ignore:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Format
        run: make fmt_check