name: Test

on:
  pull_request:
  push:
    branches:
      - master
    tags-ignore:
      - '**'

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run tests
        run: make test